### ISSUE TITLE
rc-tree-select/lib/util最新版本部分API已废弃，/src/Select.jsx中对应的api执行报错

### ISSUE THREAD

**Issue by air-eienniutau** [uxcore/uxcore-tree-select#13]
rc-tree-select@1.12.11 版本更新时废弃了utils中的部分api，见 https://github.com/react-component/tree-select/commit/3a789616310be29bc96f12cccce32db1d1a138fa#diff-42c78aeee9cd69869523e9f9538de29c
当前/src/Select.jsx#L12 中仍引用了旧的api，本地调试时报错

**Comment by lpgray** [comment]
@air-eienniutau 已经 fix 掉这个问题  0.4.3
