### ISSUE TITLE
树选择问题：单独滚动一边的话，下面滚动按扭看不到了，也滚动不了，必须先滚动外层的

### ISSUE THREAD

**Issue by robin71** [uxcore/uxcore-tree-select#16]
问题描述：同时共出现三个滚动条了，用户体验差，里边的左右两边的滚动条又不能单独滚动至底部，要外层先滚动才行。
期望：去掉最外边的滚动条，只留下左右选择框的滚动条就好了，这样就能实现单独滚动。

**Comment by robin71** [comment]
![image](https://user-images.githubusercontent.com/7088782/40042331-8e719638-5853-11e8-8969-405a29904cf0.png)
![image](https://user-images.githubusercontent.com/7088782/40042351-9d6488da-5853-11e8-8c91-43d7af02c103.png)

**Comment by lpgray** [comment]
提供一下 IE 下截图效果，谢谢

**Comment by WisestCoder** [comment]
@robin71 麻烦提供一下复现的过程

你是不是覆盖了默认样式，麻烦把代码贴一段吗？

**Comment by robin71** [comment]
uxcore站点上就能重现了：http://uxco.re/components/tree-select/
