### ISSUE TITLE
异步加载只有点击三角形才能触发，能否点击文字内容也可以触发

### ISSUE THREAD

**Issue by kwl777** [uxcore/uxcore-tree-select#22]

**Comment by lpgray** [comment]
文字内容被点击会认为选中数据，并不会理解为想要去加载异步的子数据。这个交互 confuse 的点如何解决？

**Comment by eternalsky** [comment]
这块我们 follow 集团组件的标准，只有点击箭头才能展开，点击文字内容，因为树选择本身还有选中的操作，所以不能用于展开。
