### ISSUE TITLE
文档中能否给一个明确的树结构，而不是使用函数生成？

### ISSUE THREAD

**Issue by yusangeng** [uxcore/uxcore-tree-select#34]
![image](https://user-images.githubusercontent.com/9398751/50513528-51e74900-0ad3-11e9-8402-213509e16a71.png)

从这里看不到实际的例子，需要运行，不太方便。

**Comment by eternalsky** [comment]
文档里有提，是一个由 {value,label,children, [disabled]} 组成的数组，查看 props 里的 treeData。
