### ISSUE TITLE
文字过长的时候，没有 nowrap

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore-tree-select#6]
![image](https://user-images.githubusercontent.com/7709602/33411899-2de67b16-d5c3-11e7-834c-69297be2cfb8.png)
![image](https://user-images.githubusercontent.com/7709602/33411911-3dcd5e78-d5c3-11e7-8a6b-ef93bf9827eb.png)

**Comment by eternalsky** [comment]
提错地方了，这里是 tree-select
