### ISSUE TITLE
组件搜索时报错

### ISSUE THREAD

**Issue by buzhou** [uxcore/uxcore-tree-select#7]
![image](https://user-images.githubusercontent.com/31878054/33541170-0fe10fca-d909-11e7-857e-12e1b5d7a772.png)

组件中继承重写了rc-tree-select中的getInputElement方法:

![image](https://user-images.githubusercontent.com/31878054/33541242-59f343c6-d909-11e7-97ac-c91274b360fb.png)

红框中的code的缺失导致了，后面rc-tree-select取 this.inputMirrorInstance 时属性缺失，导致报错。

@lpgray

**Comment by buzhou** [comment]
下面是uxcore-tree-select对应的code：

![image](https://user-images.githubusercontent.com/31878054/33541392-eeb96990-d909-11e7-80d0-10c1c9003568.png)


需要添加 this.inputMirrorInstance 对应的代码。

**Comment by eternalsky** [comment]
升级到最近版本看下，还有没有问题~

**Comment by buzhou** [comment]
已经收到了一版的fix，虽然不报错了，不过还是有问题，输入字符以后，直接失去焦点。输入框不见了，也不能选东西。

**Comment by eternalsky** [comment]
@buzhou 应该是样式还没生效，如果着急的话，可以业务上先把这段css 补上。https://github.com/uxcore/uxcore-tree-select/commit/b460e960020a5e02c73121284062e7fc44d5d21c#diff-a905ae59a3a64441683498d3cefcc253R388

**Comment by buzhou** [comment]
可以了，多谢@eternalsky
